name: need_for_sauce
description: Sauce finder.
publish_to: 'none'

version: 0.4.7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0-nullsafety.0
  chewie: ^1.0.0
  device_info: ^2.0.0
  dio: ^4.0.0-beta7
  expandable: ^5.0.1
  extended_image: ^4.0.0
  file_picker: ^3.0.0
  flutter_cache_manager: ^3.0.0-nullsafety.1
  flutter_html: ^2.0.0-nullsafety.0
  flutter_screenutil: ^5.0.0-nullsafety.11
  image: ^3.0.1
  image_editor: ^1.0.0
  json_annotation: ^4.0.0
  markdown: ^4.0.0
  mime: ^1.0.0
  open_file: ^3.0.1
  package_info: ^2.0.0
  palette_generator: ^0.3.0
  path_provider: ^2.0.1
  permission_handler: ^6.1.0
  provider: ^5.0.0
  receive_sharing_intent: ^1.4.3
  rect_getter: ^1.0.0
  share: ^2.0.0
  shared_preferences: ^2.0.5
  sliding_up_panel: ^1.0.0
  url_launcher: ^6.0.2
  video_player: ^2.0.2
  video_thumbnail: ^0.2.5+1

dependency_overrides:
  sliding_up_panel:
    path: plugins/sliding_up_panel-1.0.2-edit
  video_thumbnail:
    path: plugins/video_thumbnail-0.2.5+1-edit

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  flutter_launcher_icons: ^0.9.0
  json_serializable: ^4.0.2

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "assets/icon/background.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"

flutter:
  uses-material-design: true

  assets:
    - "assets/icon/app_icon.png"
    - "assets/icon/app_icon_circle.png"