name: need_for_sauce
description: Sauce finder.
publish_to: 'none'

version: 0.5.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2
  carousel_slider: ^2.2.1
  chewie: ^0.12.1
  device_info: ^1.0.0
  dio: ^3.0.8
  expandable: ^4.1.4
  extended_image: ^1.5.0
  file_picker: ^2.1.0
  flutter_cache_manager: ^2.1.1
  flutter_html: ^1.2.0
  flutter_screenutil: ^4.0.0
  flutter_xlider: ^3.4.0
  image: ^2.1.19
  image_editor: ^0.7.0
  isolate: ^2.0.3
  json_annotation: ^3.1.1
  markdown: ^3.0.0
  mime: ^0.9.6+3
  open_file: ^3.0.1
  package_info: ^0.4.0+18
  path_provider: ^1.6.0
  permission_handler: ^5.0.0
  provider: ^4.3.1
  receive_sharing_intent: ^1.4.3
  rect_getter: ^0.1.0
  share: ^0.6.3+6
  shared_preferences: ^0.5.6+1
  sliding_up_panel: ^1.0.0
  union: ^0.0.3+1
  url_launcher: ^5.4.1
  video_player: ^1.0.1
  video_thumbnail: ^0.2.5+1

dependency_overrides:
  video_thumbnail:
    path: plugins/video_thumbnail-0.2.5+1-edit

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  flutter_launcher_icons: ^0.8.1
  json_serializable: ^3.5.1

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "assets/icon/background.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"

flutter:
  uses-material-design: true

  assets:
    - "assets/icon/app_icon.png"
    - "assets/icon/app_icon_circle.png"